// Generated by .verify/gen-security-vectors.mjs — do not edit by hand.
//
// Pins the shared endpoint-policy behaviour for this plugin. The vectors come
// from the canonical .verify/security-vectors.json in the workspace root, so a
// plugin whose address handling drifts fails here, in its own CI.
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { assertSafeUrl } from '../src/url-security.js'

interface SecurityVector {
  host: string
  why: string
  lenient: 'allow' | 'block'
  strict: 'allow' | 'block'
}

const { cases } = JSON.parse(
  readFileSync(new URL('./security-vectors.json', import.meta.url), 'utf8'),
) as { cases: SecurityVector[] }

const toUrl = (host: string) => new URL(`http://${host.includes(':') ? `[${host}]` : host}/`)

describe('security vectors (public-endpoint policy)', () => {
  it('carries the full canonical vector set', () => {
    expect(cases.length).toBeGreaterThanOrEqual(50)
  })

  it.each(cases)('$host ($why) is $strict', async vector => {
    let verdict: 'allow' | 'block' = 'allow'
    try {
      await assertSafeUrl(toUrl(vector.host))
    } catch {
      verdict = 'block'
    }
    expect(verdict).toBe(vector.strict)
  })
})
